### ISSUE TITLE
Crash when opening the potion gui

### ISSUE THREAD

**Issue by Juicylene** [Snownee/SkillSlots#1]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

1.0.4

### Modloader version

forge 43.2.19

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

[crash-2023-07-31_17.42.35-client.txt](https://github.com/Snownee/SkillSlots/files/12222012/crash-2023-07-31_17.42.35-client.txt)

im getting this crash everytime i press R. the game freezes instantly then closes after a few seconds

**Comment by Snownee** [comment]
update
