### ISSUE TITLE
API Documentation and maven repos for Java?

### ISSUE THREAD

**Issue by IAFEnvoy** [Snownee/SkillSlots#4]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

2.1.0

### Modloader version

Fabric Both Latest

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I dont know how to use your mod with Java.

**Comment by Snownee** [comment]
There is no documentation on this yet. But it is very simple to use. You can take a look at the EverPotion mod. All you need to do is to [implement your skills](https://github.com/Snownee/EverPotion/blob/1.19.2-fabric/src/main/java/snownee/everpotion/skill/PotionCoreSkill.java) and [register them](https://github.com/Snownee/EverPotion/blob/1.19.2-fabric/src/main/java/snownee/everpotion/CoreModule.java#L32).

And you can use CurseMaven or Modrinth Maven.
